import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { getConfig } from './config/env.js';
import { auditToolSurface } from './security/read-only-policy.js';
import { AppError } from './utils/errors.js';
import { createLogger } from './utils/logger.js';
import { clearRegisteredToolMeta, getRegisteredToolMeta } from './mcp/tool-registry.js';
import { registerAdoProjectTools } from './mcp/tools/ado/project.tools.js';
import { registerAdoWorkItemTools } from './mcp/tools/ado/work-item.tools.js';
import { registerAnalysisTools } from './mcp/tools/analysis/analysis.tools.js';
import { registerTeamLeadTools } from './mcp/tools/teamlead/teamlead.tools.js';
import { registerEmailTools } from './mcp/tools/email/email.tools.js';
import { registerSkillTools } from './mcp/tools/skills/skill.tools.js';
import { registerResources } from './mcp/resources/index.js';
import { registerSkillResources } from './mcp/resources/skills.js';
import { registerPrompts } from './mcp/prompts/index.js';
import { getDatabase } from './database/connection.js';
import { getSkills, validateSkills } from './skills/loader.js';

const log = createLogger('server');

export const SERVER_NAME = 'k4k-team-lead-assistant';
export const SERVER_VERSION = '1.0.0';

const INSTRUCTIONS = `K4K Team Lead Assistant - read-only Azure DevOps intelligence for the K4K Platform team lead, with confirmation-gated email.

SCOPE
All Azure DevOps tools operate on the configured organization, project and team (ADO_ORGANIZATION / ADO_PROJECT / ADO_TEAM, default KEBS4KAAR / K4K / Platform). You never need to pass organization, project or team.

AZURE DEVOPS IS READ-ONLY
This server cannot create, update, delete or assign work items, change state, priority, area or iteration, add comments, or modify backlogs, sprints, repositories, pipelines or permissions. No such tool exists. When the Team Lead asks for a change, say plainly that this assistant is read-only for Azure DevOps, then offer what it can do: produce a recommendation, or draft an email. The change itself has to be made in Azure DevOps.

REAL DATA VS ANALYSIS
Tools prefixed \`ado_\` return measured Azure DevOps data. Tools prefixed \`analysis_\`, \`tl_analyze_\` and the review generators return an envelope with a \`facts\` block (measured) plus \`observations\`, \`concerns\` and \`recommendations\` (generated by this server's heuristics, with the thresholds stated in \`methodology\`). Keep the two apart when you answer, and never invent a work item, person, date or metric that is not in the tool output. If a value could not be measured, the tool says so - pass that on rather than estimating.

EMAIL REQUIRES EXPLICIT CONFIRMATION
\`email_draft*\` tools only create a draft; nothing is sent. Show the Team Lead the exact recipients, subject and body, ask for explicit confirmation, and only then call \`email_send_confirmed\` with the draft id and confirmation=true. That tool takes no recipient, subject or body, so the confirmed content is exactly what goes out. Never call it on your own initiative or on a vague "sounds good".

SKILLS COME FIRST FOR RECURRING WORKFLOWS
This server ships repeatable Team Lead workflows as skills. When the Team Lead asks for a briefing, a workload or deadline analysis, a project, sprint, productivity or weekly review, an assignment recommendation, a daily report, or help writing team email, call \`skill_list\` (or \`skill_get\` with the name if you already know it) and follow the skill's Workflow section instead of improvising a tool sequence. A skill is instructions, not data: loading one contacts nothing. \`skill-index\` is the router and explains how to combine skills for a compound request.

WHERE TO START
- "How is my team doing?" -> skill \`team-morning-brief\`, which uses \`analysis_daily_team_review\`
- "How is the project?" -> skill \`project-health-analysis\` (\`analysis_project_health\`, \`analysis_project\`)
- "Who is overloaded?" -> skill \`workload-analysis\` (\`analysis_work_distribution\`)
- "What is at risk?" -> skill \`deadline-risk-analysis\` (\`analysis_deadline_risk\`)
- "Who should take #1234?" -> skill \`work-assignment-recommendation\` (\`analysis_assignment_recommendation\`)
- "Send reminders about overdue work" -> skill \`team-email-assistant\` (draft, confirm, then send)
- One-off lookups - work-item detail, history, comments or hierarchy -> the \`ado_*\` tools directly
- Prompts (daily_team_review, sprint_review, tl_weekly_review and others) orchestrate these workflows end to end.`;

export interface BuildServerOptions {
    /** Skip opening the SQLite audit database. Used by tests that stub the repositories. */
    skipDatabaseInit?: boolean;
}

/**
 * Builds the MCP server: registers every tool, resource and prompt, then audits the
 * resulting tool surface against the read-only policy before returning.
 */
export function buildServer(options: BuildServerOptions = {}): McpServer {
    const config = getConfig();

    if (!options.skipDatabaseInit) {
        // Open (and migrate) the audit database eagerly so a misconfigured
        // DATABASE_URL fails at startup rather than mid-conversation.
        getDatabase();
    }

    const server = new McpServer(
        { name: SERVER_NAME, version: SERVER_VERSION },
        {
            instructions: INSTRUCTIONS,
            capabilities: { tools: {}, resources: {}, prompts: {}, logging: {} }
        }
    );

    clearRegisteredToolMeta();

    registerAdoProjectTools(server);
    registerAdoWorkItemTools(server);
    registerAnalysisTools(server);
    registerTeamLeadTools(server);
    registerEmailTools(server);
    registerSkillTools(server);
    registerResources(server);
    registerSkillResources(server);
    registerPrompts(server);

    assertReadOnlyToolSurface();
    assertSkillCatalogueIsValid();

    const tools = getRegisteredToolMeta();
    log.info('MCP server ready', {
        name: SERVER_NAME,
        version: SERVER_VERSION,
        tools: tools.length,
        readOnlyTools: tools.filter(tool => tool.readOnly).length,
        skills: getSkills().length,
        organization: config.ado.organization,
        project: config.ado.project,
        team: config.ado.team,
        adoConfigured: config.ado.configured,
        emailConfigured: config.email.configured
    });

    return server;
}

/**
 * Startup guarantee: no registered tool may look like an Azure DevOps mutation or
 * accept HTTP-level parameters. A violation aborts startup.
 */
export function assertReadOnlyToolSurface(): void {
    const tools = getRegisteredToolMeta();
    const violations = auditToolSurface(tools);
    if (violations.length > 0) {
        throw new AppError(
            'READ_ONLY_VIOLATION',
            `Read-only tool surface audit failed:\n${violations.map(violation => `  - ${violation.tool}: ${violation.reason}`).join('\n')}`
        );
    }

    // Exactly one tool is permitted to have a side effect: confirmed email sending.
    const mutating = tools.filter(tool => !tool.readOnly).map(tool => tool.name);
    if (mutating.length > 1 || (mutating.length === 1 && mutating[0] !== 'email_send_confirmed')) {
        throw new AppError(
            'READ_ONLY_VIOLATION',
            `Only email_send_confirmed may be non-read-only, but found: ${mutating.join(', ')}.`
        );
    }
}

/**
 * Startup guarantee for the skill catalogue: every skill is fully specified and
 * references only tools this server actually exposes. A skill that names a
 * missing tool would instruct the model to call something imaginary, so it
 * aborts startup rather than reaching a client.
 */
export function assertSkillCatalogueIsValid(): void {
    const issues = validateSkills(
        getSkills(),
        getRegisteredToolMeta().map(tool => tool.name)
    );
    if (issues.length > 0) {
        throw new AppError(
            'INVALID_INPUT',
            `Skill catalogue validation failed:\n${issues.map(issue => `  - ${issue.skill}: ${issue.reason}`).join('\n')}`
        );
    }
}
